server:
  port: 8082
  
spring:  data:    mongodb:      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:ecommerce}

kafka.bootstrapAddress: localhost:9092      
spring.json.trusted.packages: br.com.ecommerce